In [1]:
import pandas as pd
A = pd.read_csv("C:/Users/Sourabh/Downloads/training_sets.csv")

In [2]:
A.shape

(614, 13)

In [3]:
A.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849.0,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,NaN,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000.0,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000.0,0.0,141.0,360.0,1.0,Urban,Y

# Inspect missing Data

In [4]:
A.isna().sum()

Loan_ID               0
Gender               15
Married               3
Dependents           15
Education             1
Self_Employed        32
ApplicantIncome       2
CoapplicantIncome     1
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
from ANN_modules import replacer,catconsep,preprocessing

# Define X and Y

In [6]:
Y = A[["Loan_Status"]]
X = A.drop(labels=["Loan_ID","Loan_Status"],axis=1)

# convert Y in LabelEncoded format

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y1 = pd.DataFrame(le.fit_transform(Y),columns=["Loan_Status"])

C:\Users\Sourabh\anaconda3\envs\Deep_Learning_8AM\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [8]:
cat,con = catconsep(X)

In [9]:
cat

['Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'Property_Area']

In [10]:
con

['ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History']

# preprocessing (missing data treatment,Standardization,OHE)

In [11]:
replacer(X)

In [12]:
X.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [13]:
X1 = preprocessing(X)

In [14]:
X1.head()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Female,Gender_Male,Married_No,Married_Yes,Dependents_0,Dependents_1,Dependents_2,Dependents_3+,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,7.265121e-02,-0.554368,-0.000025,0.279851,0.452152,0,1,1,0,1,0,0,0,1,0,1,0,0,0,1
1,-1.387472e-07,-0.038610,-0.219272,0.279851,0.452152,0,1,0,1,0,1,0,0,1,0,1,0,1,0,0
2,-3.940959e-01,-0.554368,-0.957640,0.279851,0.452152,0,1,0,1,1,0,0,0,1,0,0,1,0,0,1
3,-4.624124e-01,0.252103,-0.314546,0.279851,0.452152,0,1,0,1,1,0,0,0,0,1,1,0,0,0,1
4,9.738930e-02,-0.554368,-0.064453,0.279851,0.452152,0,1,1,0,1,0,0,0,1,0,1,0,0,0,1

# Create a neural network

In [16]:
from keras.layers import Dense
from keras.models import Sequential
nn = Sequential()
nn.add(Dense(32,activation="relu",input_dim = X1.shape[1]))
nn.add(Dense(32,activation="relu"))
nn.add(Dense(1,activation="sigmoid"))
nn.compile(loss = "binary_crossentropy",metrics=["accuracy"])
nn.fit(X1,Y1,validation_split=0.2,epochs=30)

Epoch 1/30
16/16 [==============================] - 2s 33ms/step - loss: 0.6284 - accuracy: 0.6843 - val_loss: 0.5942 - val_accuracy: 0.7480
Epoch 2/30
16/16 [==============================] - 0s 6ms/step - loss: 0.5583 - accuracy: 0.7597 - val_loss: 0.5544 - val_accuracy: 0.8130
Epoch 3/30
16/16 [==============================] - 0s 6ms/step - loss: 0.5207 - accuracy: 0.7963 - val_loss: 0.5258 - val_accuracy: 0.8211
Epoch 4/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4941 - accuracy: 0.8045 - val_loss: 0.5089 - val_accuracy: 0.8211
Epoch 5/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4780 - accuracy: 0.8045 - val_loss: 0.4986 - val_accuracy: 0.8211
Epoch 6/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4655 - accuracy: 0.8045 - val_loss: 0.4921 - val_accuracy: 0.8211
Epoch 7/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4583 - accuracy: 0.8045 - val_loss: 0.4900 - val_accuracy: 0.8130
Epoch 8/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4536 - accuracy: 0.8065 - val_loss: 0.4875 - val_accuracy: 0.8130
Epoch 9/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4487 - accuracy: 0.8065 - val_loss: 0.4877 - val_accuracy: 0.8130
Epoch 10/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4450 - accuracy: 0.8106 - val_loss: 0.4854 - val_accuracy: 0.8049
Epoch 11/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4414 - accuracy: 0.8086 - val_loss: 0.4878 - val_accuracy: 0.8049
Epoch 12/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4385 - accuracy: 0.8106 - val_loss: 0.4890 - val_accuracy: 0.8049
Epoch 13/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4369 - accuracy: 0.8106 - val_loss: 0.4879 - val_accuracy: 0.8049
Epoch 14/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4318 - accuracy: 0.8106 - val_loss: 0.4900 - val_accuracy: 0.8049
Epoch 15/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4322 - accuracy: 0.8147 - val_loss: 0.4898 - val_accuracy: 0.8049
Epoch 16/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4281 - accuracy: 0.8106 - val_loss: 0.4926 - val_accuracy: 0.8049
Epoch 17/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4266 - accuracy: 0.8106 - val_loss: 0.4993 - val_accuracy: 0.7967
Epoch 18/30
16/16 [==============================] - 0s 7ms/step - loss: 0.4239 - accuracy: 0.8126 - val_loss: 0.4941 - val_accuracy: 0.8049
Epoch 19/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4217 - accuracy: 0.8086 - val_loss: 0.4958 - val_accuracy: 0.7886
Epoch 20/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4215 - accuracy: 0.8126 - val_loss: 0.4957 - val_accuracy: 0.7886
Epoch 21/30
16/16 [==============================] - 0s 7ms/step - loss: 0.4190 - accuracy: 0.8106 - val_loss: 0.4966 - val_accuracy: 0.7967
Epoch 22/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4172 - accuracy: 0.8167 - val_loss: 0.4993 - val_accuracy: 0.7886
Epoch 23/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4172 - accuracy: 0.8187 - val_loss: 0.4998 - val_accuracy: 0.7967
Epoch 24/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4125 - accuracy: 0.8167 - val_loss: 0.5078 - val_accuracy: 0.8049
Epoch 25/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4130 - accuracy: 0.8147 - val_loss: 0.5036 - val_accuracy: 0.7886
Epoch 26/30
16/16 [==============================] - 0s 7ms/step - loss: 0.4110 - accuracy: 0.8167 - val_loss: 0.5035 - val_accuracy: 0.7886
Epoch 27/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4097 - accuracy: 0.8167 - val_loss: 0.5079 - val_accuracy: 0.7967
Epoch 28/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4063 - accuracy: 0.8187 - val_loss: 0.5095 - val_accuracy: 0.7967
Epoch 29/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4055 - accuracy: 0.8147 - val_loss: 0.5075 - val_accuracy: 0.7886
Epoch 30/30
16/16 [==============================] - 0s 6ms/step - loss: 0.4043 - accuracy: 0.8167 - val_loss: 0.5099 - val_accuracy: 0.7967

In [17]:
X1.columns

Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Gender_Female', 'Gender_Male',
       'Married_No', 'Married_Yes', 'Dependents_0', 'Dependents_1',
       'Dependents_2', 'Dependents_3+', 'Education_Graduate',
       'Education_Not Graduate', 'Self_Employed_No', 'Self_Employed_Yes',
       'Property_Area_Rural', 'Property_Area_Semiurban',
       'Property_Area_Urban'],
      dtype='object')

In [18]:
X1.shape

(614, 20)

In [19]:
nn = Sequential()
nn.add(Dense(32,activation="relu",input_dim = X1.shape[1]))
nn.add(Dense(32,activation="relu"))
nn.add(Dense(1,activation="sigmoid"))
nn.compile(loss = "binary_crossentropy",metrics=["accuracy"])
nn.fit(X1,Y1,validation_split=0.2,epochs=100,batch_size=100)

Epoch 1/100
5/5 [==============================] - 2s 83ms/step - loss: 0.6495 - accuracy: 0.6640 - val_loss: 0.6500 - val_accuracy: 0.7073
Epoch 2/100
5/5 [==============================] - 0s 19ms/step - loss: 0.6011 - accuracy: 0.7210 - val_loss: 0.6229 - val_accuracy: 0.7236
Epoch 3/100
5/5 [==============================] - 0s 19ms/step - loss: 0.5732 - accuracy: 0.7556 - val_loss: 0.6021 - val_accuracy: 0.7805
Epoch 4/100
5/5 [==============================] - 0s 17ms/step - loss: 0.5509 - accuracy: 0.7678 - val_loss: 0.5862 - val_accuracy: 0.7967
Epoch 5/100
5/5 [==============================] - 0s 14ms/step - loss: 0.5338 - accuracy: 0.7862 - val_loss: 0.5713 - val_accuracy: 0.8049
Epoch 6/100
5/5 [==============================] - 0s 14ms/step - loss: 0.5187 - accuracy: 0.7963 - val_loss: 0.5599 - val_accuracy: 0.8049
Epoch 7/100
5/5 [==============================] - 0s 16ms/step - loss: 0.5067 - accuracy: 0.8024 - val_loss: 0.5489 - val_accuracy: 0.8049
Epoch 8/100
5/5 [==============================] - 0s 15ms/step - loss: 0.4959 - accuracy: 0.8024 - val_loss: 0.5400 - val_accuracy: 0.8049
Epoch 9/100
5/5 [==============================] - 0s 19ms/step - loss: 0.4858 - accuracy: 0.7984 - val_loss: 0.5327 - val_accuracy: 0.7886
Epoch 10/100
5/5 [==============================] - 0s 16ms/step - loss: 0.4781 - accuracy: 0.8065 - val_loss: 0.5262 - val_accuracy: 0.7886
Epoch 11/100
5/5 [==============================] - 0s 16ms/step - loss: 0.4710 - accuracy: 0.8065 - val_loss: 0.5208 - val_accuracy: 0.7886
Epoch 12/100
5/5 [==============================] - 0s 16ms/step - loss: 0.4653 - accuracy: 0.8065 - val_loss: 0.5170 - val_accuracy: 0.7886
Epoch 13/100
5/5 [==============================] - 0s 15ms/step - loss: 0.4605 - accuracy: 0.8086 - val_loss: 0.5128 - val_accuracy: 0.7886
Epoch 14/100
5/5 [==============================] - 0s 15ms/step - loss: 0.4555 - accuracy: 0.8086 - val_loss: 0.5088 - val_accuracy: 0.7886
Epoch 15/100
5/5 [==============================] - 0s 16ms/step - loss: 0.4525 - accuracy: 0.8086 - val_loss: 0.5085 - val_accuracy: 0.7886
Epoch 16/100
5/5 [==============================] - 0s 15ms/step - loss: 0.4486 - accuracy: 0.8086 - val_loss: 0.5056 - val_accuracy: 0.7805
Epoch 17/100
5/5 [==============================] - 0s 15ms/step - loss: 0.4444 - accuracy: 0.8065 - val_loss: 0.5013 - val_accuracy: 0.7886
Epoch 18/100
5/5 [==============================] - 0s 11ms/step - loss: 0.4427 - accuracy: 0.8086 - val_loss: 0.5020 - val_accuracy: 0.7886
Epoch 19/100
5/5 [==============================] - 0s 13ms/step - loss: 0.4398 - accuracy: 0.8086 - val_loss: 0.5016 - val_accuracy: 0.7886
Epoch 20/100
5/5 [==============================] - 0s 13ms/step - loss: 0.4398 - accuracy: 0.8065 - val_loss: 0.5021 - val_accuracy: 0.7886
Epoch 21/100
5/5 [==============================] - 0s 16ms/step - loss: 0.4365 - accuracy: 0.8086 - val_loss: 0.5020 - val_accuracy: 0.7886
Epoch 22/100
5/5 [==============================] - 0s 16ms/step - loss: 0.4351 - accuracy: 0.8065 - val_loss: 0.4996 - val_accuracy: 0.7886
Epoch 23/100
5/5 [==============================] - 0s 22ms/step - loss: 0.4321 - accuracy: 0.8086 - val_loss: 0.5001 - val_accuracy: 0.7886
Epoch 24/100
5/5 [==============================] - 0s 21ms/step - loss: 0.4307 - accuracy: 0.8065 - val_loss: 0.4998 - val_accuracy: 0.7886
Epoch 25/100
5/5 [==============================] - 0s 21ms/step - loss: 0.4296 - accuracy: 0.8045 - val_loss: 0.4991 - val_accuracy: 0.7886
Epoch 26/100
5/5 [==============================] - 0s 21ms/step - loss: 0.4291 - accuracy: 0.8024 - val_loss: 0.4987 - val_accuracy: 0.7886
Epoch 27/100
5/5 [==============================] - 0s 21ms/step - loss: 0.4268 - accuracy: 0.8086 - val_loss: 0.4993 - val_accuracy: 0.7886
Epoch 28/100
5/5 [==============================] - 0s 22ms/step - loss: 0.4253 - accuracy: 0.8086 - val_loss: 0.5033 - val_accuracy: 0.7724
Epoch 29/100
5/5 [==============================] - 0s 21ms/step - loss: 0.4237 - accuracy: 0.8086 - val_loss: 0.5005 - val_accuracy: 0.7805
Epoch 30/100
5/5 [==============================] - 0s 16ms/step - loss: 0.4234 - accuracy: 0.8106 - val_loss: 0.5010 - val_accuracy: 0.7724
Epoch 31/100
5/5 [==============================] - 0s 17ms/step - loss: 0.4213 - accuracy: 0.8106 - val_loss: 0.5018 - val_accuracy: 0.7724
Epoch 32/100
5/5 [==============================] - 0s 18ms/step - loss: 0.4207 - accuracy: 0.8147 - val_loss: 0.5064 - val_accuracy: 0.7805
Epoch 33/100
5/5 [==============================] - 0s 17ms/step - loss: 0.4199 - accuracy: 0.8126 - val_loss: 0.5044 - val_accuracy: 0.7805
Epoch 34/100
5/5 [==============================] - 0s 15ms/step - loss: 0.4182 - accuracy: 0.8106 - val_loss: 0.5032 - val_accuracy: 0.7805
Epoch 35/100
5/5 [==============================] - 0s 18ms/step - loss: 0.4171 - accuracy: 0.8086 - val_loss: 0.4999 - val_accuracy: 0.7724
Epoch 36/100
5/5 [==============================] - 0s 17ms/step - loss: 0.4159 - accuracy: 0.8167 - val_loss: 0.5022 - val_accuracy: 0.7805
Epoch 37/100
5/5 [==============================] - 0s 21ms/step - loss: 0.4168 - accuracy: 0.8147 - val_loss: 0.5023 - val_accuracy: 0.7805
Epoch 38/100
5/5 [==============================] - 0s 29ms/step - loss: 0.4139 - accuracy: 0.8126 - val_loss: 0.5017 - val_accuracy: 0.7805
Epoch 39/100
5/5 [==============================] - 0s 37ms/step - loss: 0.4145 - accuracy: 0.8106 - val_loss: 0.5021 - val_accuracy: 0.7724
Epoch 40/100
5/5 [==============================] - 0s 27ms/step - loss: 0.4123 - accuracy: 0.8126 - val_loss: 0.5048 - val_accuracy: 0.7805
Epoch 41/100
5/5 [==============================] - 0s 29ms/step - loss: 0.4103 - accuracy: 0.8126 - val_loss: 0.5007 - val_accuracy: 0.7724
Epoch 42/100
5/5 [==============================] - 0s 28ms/step - loss: 0.4109 - accuracy: 0.8147 - val_loss: 0.5025 - val_accuracy: 0.7724
Epoch 43/100
5/5 [==============================] - 0s 29ms/step - loss: 0.4086 - accuracy: 0.8147 - val_loss: 0.5042 - val_accuracy: 0.7805
Epoch 44/100
5/5 [==============================] - 0s 24ms/step - loss: 0.4081 - accuracy: 0.8126 - val_loss: 0.5079 - val_accuracy: 0.7886
Epoch 45/100
5/5 [==============================] - 0s 24ms/step - loss: 0.4071 - accuracy: 0.8126 - val_loss: 0.5048 - val_accuracy: 0.7805
Epoch 46/100
5/5 [==============================] - 0s 25ms/step - loss: 0.4069 - accuracy: 0.8167 - val_loss: 0.5032 - val_accuracy: 0.7724
Epoch 47/100
5/5 [==============================] - 0s 27ms/step - loss: 0.4055 - accuracy: 0.8106 - val_loss: 0.5035 - val_accuracy: 0.7724
Epoch 48/100
5/5 [==============================] - 0s 25ms/step - loss: 0.4055 - accuracy: 0.8147 - val_loss: 0.5042 - val_accuracy: 0.7724
Epoch 49/100
5/5 [==============================] - 0s 28ms/step - loss: 0.4072 - accuracy: 0.8167 - val_loss: 0.5049 - val_accuracy: 0.7724
Epoch 50/100
5/5 [==============================] - 0s 28ms/step - loss: 0.4024 - accuracy: 0.8126 - val_loss: 0.5075 - val_accuracy: 0.7967
Epoch 51/100
5/5 [==============================] - 0s 30ms/step - loss: 0.4036 - accuracy: 0.8187 - val_loss: 0.5108 - val_accuracy: 0.7967
Epoch 52/100
5/5 [==============================] - 0s 29ms/step - loss: 0.4012 - accuracy: 0.8106 - val_loss: 0.5089 - val_accuracy: 0.7967
Epoch 53/100
5/5 [==============================] - 0s 29ms/step - loss: 0.4004 - accuracy: 0.8167 - val_loss: 0.5064 - val_accuracy: 0.7967
Epoch 54/100
5/5 [==============================] - 0s 30ms/step - loss: 0.3998 - accuracy: 0.8126 - val_loss: 0.5116 - val_accuracy: 0.7967
Epoch 55/100
5/5 [==============================] - 0s 27ms/step - loss: 0.3985 - accuracy: 0.8126 - val_loss: 0.5086 - val_accuracy: 0.7967
Epoch 56/100
5/5 [==============================] - 0s 25ms/step - loss: 0.3981 - accuracy: 0.8126 - val_loss: 0.5088 - val_accuracy: 0.7967
Epoch 57/100
5/5 [==============================] - 0s 25ms/step - loss: 0.3980 - accuracy: 0.8126 - val_loss: 0.5095 - val_accuracy: 0.7967
Epoch 58/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3961 - accuracy: 0.8126 - val_loss: 0.5076 - val_accuracy: 0.7967
Epoch 59/100
5/5 [==============================] - 0s 22ms/step - loss: 0.3986 - accuracy: 0.8126 - val_loss: 0.5103 - val_accuracy: 0.7967
Epoch 60/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3940 - accuracy: 0.8187 - val_loss: 0.5080 - val_accuracy: 0.7967
Epoch 61/100
5/5 [==============================] - 0s 26ms/step - loss: 0.3941 - accuracy: 0.8126 - val_loss: 0.5079 - val_accuracy: 0.7967
Epoch 62/100
5/5 [==============================] - 0s 27ms/step - loss: 0.3934 - accuracy: 0.8167 - val_loss: 0.5081 - val_accuracy: 0.7967
Epoch 63/100
5/5 [==============================] - 0s 27ms/step - loss: 0.3928 - accuracy: 0.8167 - val_loss: 0.5145 - val_accuracy: 0.7967
Epoch 64/100
5/5 [==============================] - 0s 25ms/step - loss: 0.3962 - accuracy: 0.8187 - val_loss: 0.5110 - val_accuracy: 0.7967
Epoch 65/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3898 - accuracy: 0.8147 - val_loss: 0.5104 - val_accuracy: 0.7967
Epoch 66/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3902 - accuracy: 0.8187 - val_loss: 0.5077 - val_accuracy: 0.7967
Epoch 67/100
5/5 [==============================] - 0s 25ms/step - loss: 0.3903 - accuracy: 0.8167 - val_loss: 0.5089 - val_accuracy: 0.7967
Epoch 68/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3906 - accuracy: 0.8106 - val_loss: 0.5105 - val_accuracy: 0.7967
Epoch 69/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3876 - accuracy: 0.8208 - val_loss: 0.5139 - val_accuracy: 0.7967
Epoch 70/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3869 - accuracy: 0.8208 - val_loss: 0.5092 - val_accuracy: 0.7967
Epoch 71/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3861 - accuracy: 0.8208 - val_loss: 0.5116 - val_accuracy: 0.7967
Epoch 72/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3871 - accuracy: 0.8208 - val_loss: 0.5106 - val_accuracy: 0.8049
Epoch 73/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3862 - accuracy: 0.8187 - val_loss: 0.5131 - val_accuracy: 0.7967
Epoch 74/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3870 - accuracy: 0.8126 - val_loss: 0.5139 - val_accuracy: 0.7967
Epoch 75/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3843 - accuracy: 0.8208 - val_loss: 0.5132 - val_accuracy: 0.7967
Epoch 76/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3835 - accuracy: 0.8228 - val_loss: 0.5176 - val_accuracy: 0.7805
Epoch 77/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3828 - accuracy: 0.8248 - val_loss: 0.5146 - val_accuracy: 0.7967
Epoch 78/100
5/5 [==============================] - 0s 26ms/step - loss: 0.3829 - accuracy: 0.8187 - val_loss: 0.5187 - val_accuracy: 0.7805
Epoch 79/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3818 - accuracy: 0.8187 - val_loss: 0.5173 - val_accuracy: 0.7805
Epoch 80/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3816 - accuracy: 0.8228 - val_loss: 0.5148 - val_accuracy: 0.8049
Epoch 81/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3807 - accuracy: 0.8187 - val_loss: 0.5157 - val_accuracy: 0.7967
Epoch 82/100
5/5 [==============================] - 0s 26ms/step - loss: 0.3782 - accuracy: 0.8208 - val_loss: 0.5194 - val_accuracy: 0.7805
Epoch 83/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3793 - accuracy: 0.8208 - val_loss: 0.5193 - val_accuracy: 0.7805
Epoch 84/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3768 - accuracy: 0.8228 - val_loss: 0.5201 - val_accuracy: 0.7886
Epoch 85/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3758 - accuracy: 0.8248 - val_loss: 0.5150 - val_accuracy: 0.8049
Epoch 86/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3764 - accuracy: 0.8248 - val_loss: 0.5215 - val_accuracy: 0.7805
Epoch 87/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3756 - accuracy: 0.8228 - val_loss: 0.5239 - val_accuracy: 0.7805
Epoch 88/100
5/5 [==============================] - 0s 26ms/step - loss: 0.3740 - accuracy: 0.8208 - val_loss: 0.5261 - val_accuracy: 0.7805
Epoch 89/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3722 - accuracy: 0.8289 - val_loss: 0.5188 - val_accuracy: 0.8049
Epoch 90/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3745 - accuracy: 0.8269 - val_loss: 0.5238 - val_accuracy: 0.7805
Epoch 91/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3709 - accuracy: 0.8350 - val_loss: 0.5228 - val_accuracy: 0.7967
Epoch 92/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3717 - accuracy: 0.8289 - val_loss: 0.5223 - val_accuracy: 0.8049
Epoch 93/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3706 - accuracy: 0.8330 - val_loss: 0.5329 - val_accuracy: 0.7642
Epoch 94/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3690 - accuracy: 0.8289 - val_loss: 0.5239 - val_accuracy: 0.7967
Epoch 95/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3687 - accuracy: 0.8269 - val_loss: 0.5263 - val_accuracy: 0.7805
Epoch 96/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3682 - accuracy: 0.8310 - val_loss: 0.5290 - val_accuracy: 0.7805
Epoch 97/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3659 - accuracy: 0.8310 - val_loss: 0.5325 - val_accuracy: 0.7805
Epoch 98/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3686 - accuracy: 0.8350 - val_loss: 0.5348 - val_accuracy: 0.7642
Epoch 99/100
5/5 [==============================] - 0s 23ms/step - loss: 0.3650 - accuracy: 0.8411 - val_loss: 0.5304 - val_accuracy: 0.7805
Epoch 100/100
5/5 [==============================] - 0s 24ms/step - loss: 0.3639 - accuracy: 0.8350 - val_loss: 0.5251 - val_accuracy: 0.8049

# Testing set

In [20]:
B = pd.read_csv("C:/Users/Sourabh/Downloads/testing_sets.csv")

In [21]:
xtest = B.drop(labels=["Loan_ID"],axis=1)

In [22]:
replacer(xtest)

In [23]:
xtest = preprocessing(xtest)

In [24]:
xtest.shape

(367, 20)

In [25]:
nn.predict(xtest)

array([[0.86392426],
       [0.7885628 ],
       [0.7729893 ],
       [0.8052282 ],
       [0.5887248 ],
       [0.7502039 ],
       [0.74997073],
       [0.01202479],
       [0.9373505 ],
       [0.96889186],
       [0.57456166],
       [0.83211446],
       [0.88517237],
       [0.1954517 ],
       [0.89169055],
       [0.7357503 ],
       [0.78751945],
       [0.96760666],
       [0.38607138],
       [0.95201355],
       [0.8487091 ],
       [0.72583973],
       [0.775019  ],
       [0.8497072 ],
       [0.49733016],
       [0.30110866],
       [0.74329907],
       [0.5848712 ],
       [0.9567781 ],
       [0.8949048 ],
       [0.89900947],
       [0.79920113],
       [0.897383  ],
       [0.7878916 ],
       [0.89963984],
       [0.12897101],
       [0.947845  ],
       [0.90779614],
       [0.691519  ],
       [0.8058095 ],
       [0.8860675 ],
       [0.84888047],
       [0.97775704],
       [0.83714867],
       [0.8317641 ],
       [0.7183884 ],
       [0.66864073],
       [0.96194595],
       [0.7722723 ],
       [0.83611095],
       [0.77025235],
       [0.89665794],
       [0.80992067],
       [0.98626894],
       [0.6471392 ],
       [0.04484883],
       [0.715574  ],
       [0.9874493 ],
       [0.37143904],
       [0.97488624],
       [0.9720168 ],
       [0.75498915],
       [0.8811475 ],
       [0.08273834],
       [0.6672847 ],
       [0.967536  ],
       [0.033106  ],
       [0.09165695],
       [0.9044483 ],
       [0.1002537 ],
       [0.8998654 ],
       [0.9335295 ],
       [0.85311973],
       [0.38001812],
       [0.98400867],
       [0.80426306],
       [0.7187817 ],
       [0.82413137],
       [0.8594538 ],
       [0.8029313 ],
       [0.04279971],
       [0.44590703],
       [0.00536591],
       [0.3952908 ],
       [0.2979164 ],
       [0.9628757 ],
       [0.8516096 ],
       [0.9106011 ],
       [0.9767807 ],
       [0.5216878 ],
       [0.6986059 ],
       [0.37470412],
       [0.7476492 ],
       [0.98449004],
       [0.11377648],
       [0.93985605],
       [0.4467173 ],
       [0.96722955],
       [0.9100466 ],
       [0.863489  ],
       [0.7275565 ],
       [0.04191387],
       [0.80384696],
       [0.8934115 ],
       [0.90516007],
       [0.8865566 ],
       [0.0803698 ],
       [0.88116217],
       [0.9486207 ],
       [0.65996194],
       [0.8731983 ],
       [0.96582085],
       [0.844843  ],
       [0.96088195],
       [0.8083254 ],
       [0.82570434],
       [0.9186628 ],
       [0.04945666],
       [0.12760031],
       [0.08690712],
       [0.74854   ],
       [0.82319295],
       [0.85005224],
       [0.30304763],
       [0.24524254],
       [0.8946504 ],
       [0.04312354],
       [0.74966514],
       [0.944666  ],
       [0.9648558 ],
       [0.87492824],
       [0.6762363 ],
       [0.79188085],
       [0.6736641 ],
       [0.9348215 ],
       [0.8650967 ],
       [0.8123921 ],
       [0.806262  ],
       [0.92698   ],
       [0.78034985],
       [0.07055002],
       [0.9616122 ],
       [0.01877964],
       [0.7157335 ],
       [0.95365894],
       [0.9101355 ],
       [0.8339449 ],
       [0.02723718],
       [0.9229994 ],
       [0.78068876],
       [0.7514304 ],
       [0.8857869 ],
       [0.7010468 ],
       [0.02367762],
       [0.90520936],
       [0.9313442 ],
       [0.8031745 ],
       [0.85398215],
       [0.58862823],
       [0.5531831 ],
       [0.69648474],
       [0.08799791],
       [0.7897347 ],
       [0.67288065],
       [0.86554015],
       [0.04705456],
       [0.04272944],
       [0.86320996],
       [0.23568395],
       [0.51038593],
       [0.67239666],
       [0.75289404],
       [0.6867702 ],
       [0.14922857],
       [0.02087116],
       [0.92218566],
       [0.9303175 ],
       [0.55997354],
       [0.83089197],
       [0.86473453],
       [0.9733519 ],
       [0.9422028 ],
       [0.8197631 ],
       [0.5354955 ],
       [0.9307426 ],
       [0.768882  ],
       [0.97544897],
       [0.89955056],
       [0.50611186],
       [0.2860695 ],
       [0.5279006 ],
       [0.7754154 ],
       [0.05640036],
       [0.02873662],
       [0.25109732],
       [0.691519  ],
       [0.05266893],
       [0.78970885],
       [0.02355787],
       [0.8507029 ],
       [0.22682962],
       [0.7539567 ],
       [0.8164854 ],
       [0.9693558 ],
       [0.9190929 ],
       [0.9755802 ],
       [0.7413608 ],
       [0.8987914 ],
       [0.8318374 ],
       [0.80070746],
       [0.7782709 ],
       [0.15120804],
       [0.9626051 ],
       [0.706215  ],
       [0.9366477 ],
       [0.87884486],
       [0.93541974],
       [0.5658338 ],
       [0.49795228],
       [0.8134217 ],
       [0.8239125 ],
       [0.80888975],
       [0.17932886],
       [0.53332835],
       [0.23067915],
       [0.81176186],
       [0.901569  ],
       [0.87490124],
       [0.8741522 ],
       [0.0125545 ],
       [0.929514  ],
       [0.81099474],
       [0.97963846],
       [0.7775989 ],
       [0.8183651 ],
       [0.14651626],
       [0.5020152 ],
       [0.8752128 ],
       [0.9759572 ],
       [0.15711817],
       [0.57203144],
       [0.1538426 ],
       [0.97300065],
       [0.04307985],
       [0.88405174],
       [0.36659804],
       [0.8731439 ],
       [0.82222193],
       [0.8860066 ],
       [0.93629956],
       [0.01191515],
       [0.9851799 ],
       [0.6473167 ],
       [0.8638722 ],
       [0.75183177],
       [0.05853385],
       [0.51517653],
       [0.82880557],
       [0.8094033 ],
       [0.65468943],
       [0.9003448 ],
       [0.9763737 ],
       [0.6798759 ],
       [0.6331616 ],
       [0.7814176 ],
       [0.8972805 ],
       [0.02225193],
       [0.7877962 ],
       [0.05278584],
       [0.7390287 ],
       [0.8483144 ],
       [0.44183764],
       [0.4824983 ],
       [0.12981689],
       [0.10949326],
       [0.9757684 ],
       [0.8428252 ],
       [0.94897854],
       [0.03136075],
       [0.4136337 ],
       [0.9308292 ],
       [0.7376369 ],
       [0.7593828 ],
       [0.5440992 ],
       [0.04210359],
       [0.6395006 ],
       [0.74219775],
       [0.90668225],
       [0.78027844],
       [0.90415144],
       [0.93233347],
       [0.8742658 ],
       [0.49537402],
       [0.09693545],
       [0.8142516 ],
       [0.46366692],
       [0.914171  ],
       [0.5202918 ],
       [0.9494599 ],
       [0.83298385],
       [0.7999178 ],
       [0.03053737],
       [0.4528378 ],
       [0.70703477],
       [0.9727013 ],
       [0.87316895],
       [0.7797131 ],
       [0.7416402 ],
       [0.66764164],
       [0.9689729 ],
       [0.7791003 ],
       [0.31367564],
       [0.88920456],
       [0.8194806 ],
       [0.8779167 ],
       [0.9726919 ],
       [0.5115959 ],
       [0.03330067],
       [0.48479518],
       [0.84980667],
       [0.7009063 ],
       [0.77444524],
       [0.9078151 ],
       [0.9623022 ],
       [0.7934129 ],
       [0.46144044],
       [0.85319686],
       [0.82973564],
       [0.91907537],
       [0.9093626 ],
       [0.6903708 ],
       [0.7784641 ],
       [0.76072204],
       [0.93496597],
       [0.9794166 ],
       [0.7975982 ],
       [0.8524581 ],
       [0.8747935 ],
       [0.93382597],
       [0.1638414 ],
       [0.9791355 ],
       [0.7575521 ],
       [0.54196334],
       [0.81513023],
       [0.60787797],
       [0.81975436],
       [0.05566797],
       [0.5864624 ],
       [0.87236667],
       [0.80755424],
       [0.5764159 ],
       [0.59729666],
       [0.88604903],
       [0.89902663],
       [0.06908748],
       [0.8900841 ],
       [0.8813562 ],
       [0.7349497 ],
       [0.615533  ],
       [0.9153435 ],
       [0.89990807],
       [0.9486536 ],
       [0.8463367 ],
       [0.8890976 ],
       [0.8837637 ],
       [0.7551869 ],
       [0.9601956 ]], dtype=float32)

In [27]:
W = []

In [28]:
for i in nn.predict(xtest):
    if(i < 0.5):
        W.append("Y")
    else:
        W.append("N")

In [29]:
B["predicted_loan_Status"]= W

In [30]:
B

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,predicted_loan_Status
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban,N
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban,N
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban,N
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban,N
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.0,Urban,N
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.0,Urban,N
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,NaN,Semiurban,N
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.0,Rural,N
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.0,Rural,N

# problem statement 2:

# Data preparation

In [31]:
replacer(A)

In [32]:
A1 = A[A.Loan_Status == "Y"]

In [34]:
A2 = B[B.predicted_loan_Status == "Y"]

In [35]:
A1.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [36]:
A2.columns = A1.columns

In [37]:
C = pd.concat([A1,A2])

In [39]:
C.shape

(501, 13)

In [40]:
C.index = range(0,501,1)

In [41]:
C.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849.0,0.0,146.41,360.0,1.0,Urban,Y
1,LP001005,Male,Yes,0,Graduate,Yes,3000.0,0.0,66.00,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120.00,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000.0,0.0,141.00,360.0,1.0,Urban,Y
4,LP001011,Male,Yes,2,Graduate,Yes,5417.0,4196.0,267.00,360.0,1.0,Urban,Y

# preprocessing

In [42]:
X = C.drop(labels=["LoanAmount","Loan_ID"],axis=1)
replacer(X)
Y = C[["LoanAmount"]]
replacer(Y)

C:\Users\Sourabh\OneDrive\Desktop\Data Science\Deep Learning\ANN_modules.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]=df[i].fillna(x)

In [43]:
X1 = preprocessing(X)

In [44]:
X1.shape

(501, 20)

In [45]:
Y.isna().sum()

LoanAmount    0
dtype: int64

# Create NN

In [46]:
from tensorflow.keras.losses import MAE,mean_absolute_error

In [48]:
from keras.layers import Dense
from keras.models import Sequential
nn1 = Sequential()
nn1.add(Dense(32,activation="relu",input_dim = X1.shape[1]))
nn1.add(Dense(32,activation="relu"))
nn1.add(Dense(1))
nn1.compile(loss = "mean_squared_error")
nn1.fit(X1,Y,validation_split=0.2,epochs=30)

Epoch 1/30
13/13 [==============================] - 1s 25ms/step - loss: 27393.7129 - val_loss: 33238.8516
Epoch 2/30
13/13 [==============================] - 0s 7ms/step - loss: 27113.9746 - val_loss: 32925.5156
Epoch 3/30
13/13 [==============================] - 0s 7ms/step - loss: 26820.4121 - val_loss: 32567.4102
Epoch 4/30
13/13 [==============================] - 0s 7ms/step - loss: 26466.4434 - val_loss: 32132.2207
Epoch 5/30
13/13 [==============================] - 0s 6ms/step - loss: 26022.9531 - val_loss: 31590.0176
Epoch 6/30
13/13 [==============================] - 0s 6ms/step - loss: 25469.2422 - val_loss: 30920.0469
Epoch 7/30
13/13 [==============================] - 0s 6ms/step - loss: 24797.6055 - val_loss: 30137.6191
Epoch 8/30
13/13 [==============================] - 0s 6ms/step - loss: 23975.2852 - val_loss: 29201.4316
Epoch 9/30
13/13 [==============================] - 0s 6ms/step - loss: 23003.0566 - val_loss: 28104.2578
Epoch 10/30
13/13 [==============================] - 0s 6ms/step - loss: 21904.4316 - val_loss: 26913.0938
Epoch 11/30
13/13 [==============================] - 0s 7ms/step - loss: 20672.3945 - val_loss: 25541.7305
Epoch 12/30
13/13 [==============================] - 0s 6ms/step - loss: 19328.1523 - val_loss: 24092.8770
Epoch 13/30
13/13 [==============================] - 0s 6ms/step - loss: 17886.6348 - val_loss: 22499.4727
Epoch 14/30
13/13 [==============================] - 0s 6ms/step - loss: 16388.6387 - val_loss: 20882.1230
Epoch 15/30
13/13 [==============================] - 0s 6ms/step - loss: 14869.3447 - val_loss: 19091.5352
Epoch 16/30
13/13 [==============================] - 0s 7ms/step - loss: 13317.3574 - val_loss: 17375.1973
Epoch 17/30
13/13 [==============================] - 0s 6ms/step - loss: 11843.7275 - val_loss: 15615.2656
Epoch 18/30
13/13 [==============================] - 0s 6ms/step - loss: 10435.5254 - val_loss: 13840.5176
Epoch 19/30
13/13 [==============================] - 0s 7ms/step - loss: 9182.7227 - val_loss: 12197.7393
Epoch 20/30
13/13 [==============================] - 0s 6ms/step - loss: 8113.0610 - val_loss: 10699.1094
Epoch 21/30
13/13 [==============================] - 0s 6ms/step - loss: 7312.0405 - val_loss: 9605.4521
Epoch 22/30
13/13 [==============================] - 0s 6ms/step - loss: 6756.8086 - val_loss: 8506.5449
Epoch 23/30
13/13 [==============================] - 0s 6ms/step - loss: 6402.8188 - val_loss: 7919.7378
Epoch 24/30
13/13 [==============================] - 0s 6ms/step - loss: 6206.7012 - val_loss: 7375.1831
Epoch 25/30
13/13 [==============================] - 0s 7ms/step - loss: 6065.4688 - val_loss: 7134.8618
Epoch 26/30
13/13 [==============================] - 0s 6ms/step - loss: 5948.4336 - val_loss: 6754.2080
Epoch 27/30
13/13 [==============================] - 0s 6ms/step - loss: 5850.0933 - val_loss: 6665.8906
Epoch 28/30
13/13 [==============================] - 0s 7ms/step - loss: 5758.4624 - val_loss: 6506.5049
Epoch 29/30
13/13 [==============================] - 0s 7ms/step - loss: 5670.0674 - val_loss: 6367.9023
Epoch 30/30
13/13 [==============================] - 0s 6ms/step - loss: 5594.5044 - val_loss: 6279.2759

# prepare Data for predictions

In [50]:
B1 = B[B.predicted_loan_Status == "N"]
replacer(B1)

C:\Users\Sourabh\OneDrive\Desktop\Data Science\Deep Learning\ANN_modules.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]=df[i].fillna(x)
C:\Users\Sourabh\OneDrive\Desktop\Data Science\Deep Learning\ANN_modules.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]=df[i].fillna(x)

In [51]:
newX = B1.drop(labels=["Loan_ID","LoanAmount"],axis=1)

In [52]:
newX.columns = X.columns

In [53]:
newX.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'Loan_Amount_Term',
       'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [55]:
newX.shape

(288, 11)

In [57]:
newX.index = range(0,288,1)

In [58]:
Xpred = preprocessing(newX)

In [59]:
Xpred.columns=X1.columns

# predictions

In [61]:
pred = nn1.predict(Xpred)

In [62]:
pred

array([[144.70695 ],
       [140.26204 ],
       [156.22464 ],
       [147.71649 ],
       [114.397285],
       [129.9152  ],
       [106.60769 ],
       [183.88506 ],
       [123.53997 ],
       [113.52468 ],
       [136.4285  ],
       [129.04646 ],
       [129.76677 ],
       [138.37468 ],
       [160.29909 ],
       [140.30037 ],
       [131.96465 ],
       [122.514595],
       [102.79775 ],
       [130.17653 ],
       [113.04615 ],
       [150.24274 ],
       [173.40288 ],
       [140.31053 ],
       [133.53732 ],
       [107.6143  ],
       [156.81548 ],
       [136.54626 ],
       [145.51329 ],
       [138.99306 ],
       [174.40263 ],
       [139.77946 ],
       [135.49684 ],
       [139.54834 ],
       [148.70586 ],
       [124.66382 ],
       [124.42704 ],
       [156.75484 ],
       [124.76759 ],
       [158.32845 ],
       [132.55414 ],
       [120.63657 ],
       [161.24055 ],
       [143.17915 ],
       [138.2837  ],
       [128.86452 ],
       [151.0813  ],
       [142.75157 ],
       [126.144615],
       [118.98567 ],
       [154.40608 ],
       [137.9304  ],
       [125.92343 ],
       [148.64583 ],
       [136.36093 ],
       [128.74228 ],
       [151.16447 ],
       [154.1682  ],
       [123.08788 ],
       [133.07207 ],
       [138.4692  ],
       [147.01671 ],
       [147.23381 ],
       [145.58232 ],
       [140.679   ],
       [155.95439 ],
       [150.9625  ],
       [185.80847 ],
       [144.9481  ],
       [126.482796],
       [130.56398 ],
       [134.04858 ],
       [144.09972 ],
       [152.03304 ],
       [141.77617 ],
       [145.90416 ],
       [152.11171 ],
       [166.1997  ],
       [152.87909 ],
       [135.45302 ],
       [136.03331 ],
       [121.02917 ],
       [134.68895 ],
       [136.83096 ],
       [144.35965 ],
       [139.23497 ],
       [133.57549 ],
       [126.370544],
       [137.26338 ],
       [123.59312 ],
       [151.08266 ],
       [165.83232 ],
       [156.9842  ],
       [105.14063 ],
       [126.478615],
       [152.03369 ],
       [144.60362 ],
       [134.03429 ],
       [158.27245 ],
       [121.260574],
       [131.4854  ],
       [140.32307 ],
       [130.44856 ],
       [140.57404 ],
       [124.45673 ],
       [124.46116 ],
       [137.81107 ],
       [146.83751 ],
       [145.6822  ],
       [134.50888 ],
       [129.64742 ],
       [150.56252 ],
       [267.46744 ],
       [163.98653 ],
       [166.85777 ],
       [114.67975 ],
       [144.16393 ],
       [139.56758 ],
       [149.55013 ],
       [138.73575 ],
       [138.0378  ],
       [148.51196 ],
       [114.750145],
       [162.15462 ],
       [153.00589 ],
       [153.08336 ],
       [144.8876  ],
       [157.06789 ],
       [138.07237 ],
       [122.96424 ],
       [138.87395 ],
       [149.21965 ],
       [132.89627 ],
       [128.86017 ],
       [133.96376 ],
       [145.08745 ],
       [173.75809 ],
       [139.93791 ],
       [123.95476 ],
       [149.79962 ],
       [192.58046 ],
       [156.09619 ],
       [154.39438 ],
       [143.45244 ],
       [156.15694 ],
       [171.76392 ],
       [126.36125 ],
       [138.11958 ],
       [166.41771 ],
       [169.35808 ],
       [128.89851 ],
       [130.99725 ],
       [135.49684 ],
       [125.743805],
       [133.45567 ],
       [123.96446 ],
       [138.99025 ],
       [141.49838 ],
       [123.131004],
       [143.41861 ],
       [155.38554 ],
       [138.2777  ],
       [127.34764 ],
       [132.97899 ],
       [118.61695 ],
       [142.28038 ],
       [141.37724 ],
       [144.88368 ],
       [128.55109 ],
       [123.53092 ],
       [169.19197 ],
       [146.88612 ],
       [139.66902 ],
       [135.89369 ],
       [132.31596 ],
       [119.4801  ],
       [139.33986 ],
       [157.07497 ],
       [140.7447  ],
       [259.964   ],
       [137.6491  ],
       [129.63136 ],
       [143.51181 ],
       [133.31752 ],
       [ 87.12524 ],
       [216.87872 ],
       [128.24777 ],
       [117.076385],
       [139.04768 ],
       [105.99906 ],
       [154.45122 ],
       [164.8946  ],
       [120.05949 ],
       [123.2778  ],
       [134.57283 ],
       [126.66361 ],
       [147.3597  ],
       [139.49226 ],
       [134.25896 ],
       [156.6606  ],
       [154.79053 ],
       [143.63286 ],
       [135.19334 ],
       [140.4657  ],
       [134.56627 ],
       [209.69688 ],
       [145.80179 ],
       [146.80989 ],
       [135.00768 ],
       [131.00041 ],
       [124.243484],
       [141.8235  ],
       [148.386   ],
       [129.99658 ],
       [133.37302 ],
       [144.02618 ],
       [133.55959 ],
       [144.1112  ],
       [158.9048  ],
       [132.60143 ],
       [147.28743 ],
       [135.24232 ],
       [178.26543 ],
       [146.13268 ],
       [153.16615 ],
       [127.17742 ],
       [142.57631 ],
       [119.62189 ],
       [123.711716],
       [145.04515 ],
       [149.25414 ],
       [117.99227 ],
       [134.06255 ],
       [123.15092 ],
       [157.23302 ],
       [131.02052 ],
       [152.54036 ],
       [160.94218 ],
       [136.80356 ],
       [125.884514],
       [149.19588 ],
       [123.58639 ],
       [150.6013  ],
       [136.3815  ],
       [141.10231 ],
       [141.27556 ],
       [117.97767 ],
       [130.9604  ],
       [214.03099 ],
       [145.59688 ],
       [120.731186],
       [150.46333 ],
       [159.77562 ],
       [143.39972 ],
       [146.42702 ],
       [166.10536 ],
       [132.36438 ],
       [135.958   ],
       [135.72171 ],
       [128.22865 ],
       [119.83069 ],
       [136.97198 ],
       [142.57207 ],
       [147.80617 ],
       [152.57643 ],
       [122.19294 ],
       [139.80199 ],
       [146.8015  ],
       [159.66702 ],
       [112.47285 ],
       [133.69557 ],
       [128.4244  ],
       [166.49217 ],
       [207.37627 ],
       [150.09065 ],
       [164.99048 ],
       [162.7855  ],
       [145.99475 ],
       [123.53066 ],
       [127.72271 ],
       [145.32568 ],
       [176.82643 ],
       [140.3488  ],
       [132.33838 ],
       [141.17747 ],
       [138.13951 ],
       [156.9804  ],
       [149.3025  ]], dtype=float32)